kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-from-cardservices
spec:
  podSelector:
    matchLabels:
      deployment: hello 
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app: cardservices